INTMDB-167: URL encode private enpoint ID
mongodb/go-client-mongodb-atlas pull request #173
Opened 2021-01-25 11:08 UTC by andreaangiolillo

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s): 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [x] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added any necessary documentation (if appropriate)
- [x] I have run `make fmt` and formatted my code

## Further comments
Tested with mongocli

```
./bin/mongocli atlas privateendpoint azure interface describe 6009a7a62cde816e1914b656 --privateEndpointId /subscriptions/19265c27-b60e-4c3b-9426-ae3f507300b5/resourceGroups/test/providers/Microsoft.Network/privateEndpoints/test

ID                                                                                                                          IP ADDRESS   STATUS   ERROR
/subscriptions/19265c27-b60e-4c3b-9426-ae3f507300b5/resourceGroups/test/providers/Microsoft.Network/privateEndpoints/test   10.0.0.4

```

2021-01-25 11:17 UTC, gssbzn commented
Can you please update the [test](https://github.com/mongodb/go-client-mongodb-atlas/blob/18e784932143d071c322e12ee3bc455162311c70/mongodbatlas/private_endpoints_test.go#L480) to match an actual ID with the azure format so we know this works as expected?

2021-01-25 11:36 UTC, gssbzn requested changes
Change looks good but we should update the tests as it looks like right now it mimics AWS

2021-01-25 14:33 UTC, gssbzn approved these changes
LGTM, cc @themantissa

2021-01-25 17:53 UTC, andreaangiolillo commented
@gssbzn I have just noticed that [Delete one private endpoint](https://docs.atlas.mongodb.com/reference/api/private-endpoints-endpoint-delete-one) has the same problem

2021-01-25 18:05 UTC, gssbzn approved these changes
restamp

2021-01-25 19:27 UTC, themantissa approved these changes
LGTM - will tag the DoU team as I'm surprised this didn't cause issues.

2021-01-25 19:55 UTC, leofigy approved these changes
LGTM, Hi @themantissa. 
We were already escaping it. in the terraform side. So in a ticket once we upgrade the client, we will remove the escaping to avoid escaping twice, thanks ! (@coderGo93 just fyi)

`      
encodedPrivateLinkID := url.PathEscape(privateLinkID)                                                             
        privateEndpoint, _, err := conn.PrivateEndpoints.GetOnePrivateEndpoint(context.Background(), projectID, providerName, endpointServiceID, encodedPrivateLinkID)
`

2021-01-25 20:01 UTC, merged

2021-01-26 00:59 UTC, themantissa commented
Created INTMDB-169 to handle on Terraform side.