CLOUDP-185079: notify users about new SDK
mongodb/go-client-mongodb-atlas pull request #499
Opened 2023-06-16 10:14 UTC by wtrocki

## Description

Since we have other SDK in GA state we need to flag in the old repository. 
Putting a message into Readme.md will be good start.

This PR needs docs review

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2023-06-16 10:42 UTC, sarahsimpers reviewed
A few suggestions on wording then LGTM

2023-06-16 10:42 UTC, sarahsimpers commented on README.md
> +Please follow an official [migration guide](https://github.com/mongodb/atlas-sdk-go/blob/main/docs/doc_3_migration.md)
A couple suggestions for wording.. mostly to make sure they know "currently under limited maintenance" doesn't mean it's temporary
```suggestion
`go-client-mongodb-atlas` is now deprecated and receives limited maintenance. 
For new projects, please use the official [Atlas Go SDK](https://github.com/mongodb/atlas-sdk-go).
To learn how to migrate from go-client-mongodb-atlas to the Atlas Go SDK, see the [migration guide](https://github.com/mongodb/atlas-sdk-go/blob/main/docs/doc_3_migration.md).
```

2023-06-16 12:10 UTC, andreaangiolillo requested changes
Holding this until official GA

2023-06-20 15:13 UTC, andreaangiolillo submitted a review, later dismissed

2023-06-20 15:21 UTC, matt-condon approved these changes

2023-06-20 15:50 UTC, sarahsimpers approved these changes

2023-06-20 17:18 UTC, merged